version: "3.8"

services:
  docker-osx:
    image: sickcodes/docker-osx:latest
    container_name: docker-osx
    privileged: true
    devices:
      - /dev/kvm
    ports:
      - "50922:10022"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=${DISPLAY:-:0.0}
      - SHORTNAME=catalina
    stdin_open: true  # equivalent to -it
    tty: true         # equivalent to -it
