services:
  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
      - 8081:8080
      - 50000:50000
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock # Allows Jenkins to interact with Docker
    container_name: jenkins
    restart: unless-stopped
    environment:
      - JENKINS_OPTS=--httpPort=8080

volumes:
  jenkins_home:
